---
- hosts: nimbus
  sudo: True
  user: vagrant
  tasks:
   - name: copy the file
     copy: src='{{jar}}' dest=/tmp/'{{jar | basename}}'
   - name: run the jar
     shell: "{{storm_home}}/bin/storm jar /tmp/{{jar | basename}} {{class_params}}"
